name: Facebook Ads Daily ETL - Batch A

on:
  workflow_dispatch:
  schedule:
    - cron: "10 1 * * *" # Every day at 01:10 UTC

jobs:
  facebook_etl:
    strategy:
      matrix:
        group: [d1a, m4a, d2a]
      fail-fast: false
      max-parallel: 1
    uses: ./.github/workflows/_reusable-etl.yml
    with:
      pipeline: facebook
      group: ${{ matrix.group }}
    secrets: inherit
