name: Facebook Ads Daily ETL - Batch B

on:
  workflow_dispatch:
  schedule:
    - cron: "10 2 * * *" # Every day at 02:10 UTC

jobs:
  facebook_etl:
    strategy:
      matrix:
        group: [d1b, m4b, d2b]
      fail-fast: false
      max-parallel: 1
    uses: ./.github/workflows/_reusable-etl.yml
    with:
      pipeline: facebook
      group: ${{ matrix.group }}
    secrets: inherit
